// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVq5oNFZOCm8efX7GDcAw0RJiQc3Ps9o',
    appId: '1:358663544884:web:b95c54532ddcb0f8706a61',
    messagingSenderId: '358663544884',
    projectId: 'tinderfordogs-702fe',
    authDomain: 'tinderfordogs-702fe.firebaseapp.com',
    storageBucket: 'tinderfordogs-702fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsIcc1DsvegWkWyIH8oBKqNF5PUuyeOI4',
    appId: '1:358663544884:android:ef320ae8de9380b4706a61',
    messagingSenderId: '358663544884',
    projectId: 'tinderfordogs-702fe',
    storageBucket: 'tinderfordogs-702fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEue_ig-viVUsVu3RFdLj4ewT3iBZ-gsc',
    appId: '1:358663544884:ios:6fe9eecc3401be4b706a61',
    messagingSenderId: '358663544884',
    projectId: 'tinderfordogs-702fe',
    storageBucket: 'tinderfordogs-702fe.appspot.com',
    iosClientId: '358663544884-grdli6phk2l4aoojr8l7c3an55prnrpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchdotdog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEue_ig-viVUsVu3RFdLj4ewT3iBZ-gsc',
    appId: '1:358663544884:ios:6fe9eecc3401be4b706a61',
    messagingSenderId: '358663544884',
    projectId: 'tinderfordogs-702fe',
    storageBucket: 'tinderfordogs-702fe.appspot.com',
    iosClientId: '358663544884-grdli6phk2l4aoojr8l7c3an55prnrpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchdotdog',
  );
}
